[package]
name = "mqtt-endpoint-tokio"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
mqtt_protocol_core = { path = "../mqtt-protocol-core" }
serde = { version = "1.0", features = ["derive"] }
